# Generated by Django 2.2.3 on 2019-08-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField()),
                ('active', models.BooleanField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('ticket', models.IntegerField()),
                ('order_type', models.BooleanField()),
                ('lot', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('takeprofit', models.FloatField()),
                ('active', models.BooleanField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
