# Generated by Django 2.2.3 on 2019-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField(blank=True)),
                ('active', models.CharField(choices=[('A', '有効'), ('B', '無効'), ('C', '退会')], max_length=10)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(blank=True)),
                ('order_type', models.IntegerField()),
                ('lot', models.FloatField(blank=True)),
                ('stoploss', models.FloatField(blank=True)),
                ('takeprofit', models.FloatField(blank=True)),
                ('active', models.CharField(max_length=10)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
