# Generated by Django 2.2.3 on 2019-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190823_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_list',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trade_list',
            name='stoploss',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade_list',
            name='takeprofit',
            field=models.CharField(max_length=100),
        ),
    ]
