# Generated by Django 2.2.3 on 2019-08-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20190823_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade_list',
            old_name='price',
            new_name='open_price',
        ),
    ]
