# Generated by Django 2.2.3 on 2019-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20190826_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField()),
                ('order_type', models.IntegerField()),
                ('lot', models.FloatField()),
                ('stoploss', models.TextField(max_length=100)),
                ('takeprofit', models.CharField(max_length=100)),
                ('open_price', models.CharField(max_length=100)),
                ('pair', models.CharField(max_length=30)),
            ],
        ),
    ]
